- name: configure OAuth playbook
  hosts: localhost
  tasks:
    - name: import static var data
      include_vars:
        dir: ./vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: create the secret to store client Secret from external identity provider
      command: oc create secret generic {{ secretName }} --from-literal=clientSecret={{clientSecret}} -n openshift-config

    - name: configure oauth 
      kubernetes.core.k8s:
        api_key: "{{ token }}"
        state: present
        apply: false
        resource_definition: "{{ lookup('template', 'templates/oauth.yaml.j2') | from_yaml }}"